export const INDEX = 'index'
export const DISTRICTS = 'districts'
export const DISTRICTS_DETAIL = 'districts_detail'
export const VACANCIES = 'vacancies'
export const FAVORITE = 'favorite'
export const NOT_FOUND = 'not_found'
export const SERVER_ERROR = 'server_error'